
import Navbar from './component/Navbar'
import Provider from './component/Provider'
import './global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-cyan-950 text-white'>
        <Navbar/>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
